[package]
edition = "2021"
name = "v8core"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.1"
v8 = "0.69"

[build-dependencies]
csbindgen = "1.7.0"
